on: [push]

jobs:
  deploy_aks_dev:
    name: "Deploy AKS - Dev Cluster"
    concurrency: dev
    env:
      INPUT_ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      INPUT_ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      INPUT_ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      INPUT_ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      INPUT_RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
      INPUT_CLUSTER_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}deploy${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Deploy cluster"
        run: ./action.sh
      - name: "Delete cluster"
        run: export INPUT_ACTION_TYPE="destroy" && ./action.sh  
  validate_action:
    name: "Validate action"
    concurrency: action
    runs-on: ubuntu-latest
    steps:
      - uses: gambtho/aks_devcluster_action@main
        with:
          CLUSTER_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}validate${{ github.sha }}
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  cleanup_action:
    name: "Clean-up action"
    concurrency: action
    runs-on: ubuntu-latest
    steps:
      - uses: gambtho/aks_devcluster_action@main
        with:
          CLUSTER_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}validate${{ github.sha }}
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ACTION_TYPE: "destroy"