on: [push]

jobs:
  deploy_aks_dev:
    name: "Deploy AKS - Dev Cluster"
    concurrency: dev
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
      CLUSTER_NAME: devCluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Deploy cluster"
        run: ls -l && pwd && ./action.sh
  validate_action:
    name: "Validate action"
    concurrency: action
    runs-on: ubuntu-latest
    steps:
      - uses: gambtho/aks_devcluster_action@main
        with:
          CLUSTER_NAME: "actionTest"
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}